name: Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk:
    uses: ./.github/workflows/snyk-analysis.yml

  codeql:
    uses: ./.github/workflows/codeql-analysis.yml

  dast:
    uses: ./.github/workflows/dast-analysis.yml
