name: Snyk Security Scan

on:
  workflow_call:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk for Python dependencies
        run: snyk test --file=app/requirements.txt --package-manager=pip --sarif-file-output=snyk-python.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk for JavaScript dependencies
        run: snyk test --file=app_frontend/package.json --package-manager=npm --sarif-file-output=snyk-js.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Python results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python.sarif

      - name: Upload Snyk JS results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-js.sarif
